tap "buo/cask-upgrade"
tap "d12frosted/emacs-plus"
brew "basedpyright"
brew "bash-language-server"
brew "bat"
brew "bottom"
brew "btop"
brew "coreutils"
brew "dockerfile-language-server"
brew "duf"
brew "dust"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "git-delta"
brew "gitui"
brew "go"
brew "gopls"
brew "gping"
brew "hyperfine"
brew "mpg123"
# brew "neovim"
brew "procs"
brew "python-lsp-server"
brew "ripgrep"
brew "rust"
brew "rust-analyzer"
brew "sd"
brew "starship"
brew "tealdeer"
brew "tmux"
brew "typescript-language-server"
brew "vscode-langservers-extracted"
brew "watchexec"
brew "yaml-language-server"
brew "yazi"
brew "zoxide"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-c9rgreen-sonoma-icon", "with-xwidgets"]
cask "captin"
cask "fliqlo"
# cask "font-cascadia-code"
# cask "font-fira-code"
# cask "font-hack-nerd-font"
cask "font-lxgw-neoxihei"
# cask "font-lxgw-wenkai"
cask "font-sf-mono"
cask "font-symbols-only-nerd-font"
cask "foobar2000"
cask "hiddenbar"
cask "karabiner-elements"
cask "licecap"
cask "listen1"
cask "macgesture"
cask "maczip"
cask "monitorcontrol"
cask "mos"
cask "squirrel-app"
# cask "streammusic"
cask "upscayl"
# cask "windows-app"
cask "youdaodict"
# cask "youdaonote"
vscode "ecmel.vscode-html-css"
vscode "golang.go"
vscode "mattn.lisp"
vscode "ms-python.python"
vscode "tuttieee.emacs-mcx"
